service: test-python-serverless

provider:
  name: aws
  runtime: python3.8
  versionFunctions: false
  memorySize: 128
  region: ap-southeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: echo/hello
          method: get